import '@radix-ui/themes/styles.css'
import '../styles/globals.css'
import '@/styles/radix-config.css'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import { Provider } from '@/components/provider'
import { Analytics } from '@/components/analytics'
import { ModeToggle } from '@/components/mode-toggle'
import { bluuNextFont, geliatFont, ibmPlexMono, visbyFont } from '@/styles/fonts'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen font-medium bg-background dark:bg-slate-950 font-sans text-slate-900 dark:text-slate-50 ${visbyFont.variable} ${bluuNextFont.variable} ${ibmPlexMono.variable}`}
      >
        <Provider attribute="class" defaultTheme="system" enableSystem>
          <div className="max-w-6xl mx-auto py-10 px-4 z-50">
            <header>
              <div className="flex items-center justify-between">
                <nav className="text-lg font-semibold space-x-6">
                  <Link href="/">Home</Link>
                  <Link href="/about">Portfolio</Link>
                  <Link href="/about">Blog</Link>
                </nav>
                <ModeToggle />
              </div>
            </header>
          </div>
          <main>{children}</main>
          <Analytics />
        </Provider>
      </body>
    </html>
  )
}
